// Medium.com Authentic Ultra-Fast Story Reader Engine (100% Vanilla JS & SEO Schema)

const API_BASE = window.location.origin;
let globalSettings = {};

// 1. Reading Progress Bar with rAF Throttle (Zero Main-Thread Jitter)
let ticking = false;
window.addEventListener('scroll', () => {
    if (!ticking) {
        window.requestAnimationFrame(() => {
            const docHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
            const scrollPos = window.scrollY;
            const progress = docHeight > 0 ? (scrollPos / docHeight) * 100 : 0;
            const bar = document.getElementById('scrollProgress');
            if (bar) bar.style.width = `${progress}%`;
            ticking = false;
        });
        ticking = true;
    }
}, { passive: true });

// 2. Default Initial Stories Database
let mediumStories = [
    {
        id: "1",
        slug: "parallel-multi-agent-dag-architectures",
        title: "Parallel Multi-Agent DAG Architectures & Zero-Latency Execution",
        subtitle: "Why serial chain-of-thought is giving way to directed acyclic graphs of specialized reasoning agents in autonomous coding engines.",
        author: "Dr. Kaelen Vance",
        authorInitials: "KV",
        date: "Aug 17, 2026",
        readTime: "7 min read",
        category: "ai",
        tags: "ai, agents, parallel processing, architecture",
        image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&auto=format&fit=crop&q=75",
        imageAlt: "Parallel Multi Agent Architecture diagram",
        bodyHtml: "<p>When building large-scale software synthesis systems with foundation models, single-turn prompting and linear chain-of-thought reasoning quickly hit strict context and latency ceilings. As tasks scale from single-file bugfixes to multi-tier microservice refactors, human engineering teams do not operate in a single thread—they branch into specialized roles.</p><h2>The Multi-Agent DAG Topology</h2><p>By representing a development milestone as a directed acyclic graph (DAG), independent worker agents can research documentation, scaffold backend models, and write frontend styling tokens concurrently in isolated memory branches.</p><blockquote>\"True autonomy is not about generating code in a loop; it is about establishing verifiable consensus across specialized verification gates before execution.\"</blockquote><pre><code>def dispatch_parallel_fleet(tasks: list[Task]) -> FleetResult:\n    graph = TaskDAG.build_from_specs(tasks)\n    futures = [agent_pool.execute_async(node) for node in graph.independent_nodes]\n    return await asyncio.gather(*futures)</code></pre><h2>Zero-Trust Verification in Production</h2><p>Every code block generated by a subagent passes through automated AST linters and sandbox security audits before reaching disk. If a defect is caught, the self-healing loop triggers targeted surgical patches without interrupting other parallel tracks.</p>"
    }
];

// 3. Load Current Story by Clean URL Slug or Query Param
const urlParams = new URLSearchParams(window.location.search);
const pathSlug = window.location.pathname.replace(/^\/+|\/+$/g, '').split('/').pop();
const cleanPathSlug = (pathSlug && !pathSlug.includes('.') && pathSlug !== 'post') ? pathSlug : null;
const currentSlug = urlParams.get('slug') || cleanPathSlug || "parallel-multi-agent-dag-architectures";
let currentStory = mediumStories[0];

function renderStoryDetails(story) {
    if (!story) return;

    // Dynamic SEO Metadata & Google Title
    document.title = `${story.title} – Medium`;
    
    const titleEl = document.getElementById('storyTitle');
    const subtitleEl = document.getElementById('storySubtitle');
    const authorEl = document.getElementById('storyAuthor');
    const authorAvatarEl = document.getElementById('storyAuthorAvatar');
    const authorCardAvatarEl = document.getElementById('authorCardAvatar');
    const authorCardNameEl = document.getElementById('authorCardName');
    const dateEl = document.getElementById('storyDate');
    const readTimeEl = document.getElementById('storyReadTime');
    const heroImgEl = document.getElementById('storyHeroImage');
    const proseEl = document.querySelector('.medium-prose');

    if (titleEl) titleEl.textContent = story.title;
    if (subtitleEl) subtitleEl.textContent = story.subtitle || '';
    if (authorEl) authorEl.textContent = story.author;
    if (authorAvatarEl) authorAvatarEl.textContent = story.authorInitials || "AU";
    if (authorCardAvatarEl) authorCardAvatarEl.textContent = story.authorInitials || "AU";
    if (authorCardNameEl) authorCardNameEl.textContent = `Written by ${story.author}`;
    if (dateEl) dateEl.textContent = story.date;
    if (readTimeEl) readTimeEl.textContent = story.readTime;
    if (heroImgEl) {
        heroImgEl.src = story.image;
        heroImgEl.alt = story.imageAlt || story.title;
        heroImgEl.loading = "lazy";
        heroImgEl.decoding = "async";
    }

    if (proseEl && story.bodyHtml) {
        let contentHtml = story.bodyHtml;

        // In-Article AdSense Injection (Mid-way after first <h2> or <blockquote>)
        if (globalSettings?.monetization?.in_article_ad_enabled) {
            const adBlock = `
                <div class="p-4 my-6 rounded-xl border border-dashed theme-border theme-search-bg text-center text-xs theme-muted not-prose">
                    <span class="text-[10px] font-mono uppercase text-zinc-400 block mb-1">Sponsored Advertisement</span>
                    <div class="adsense-slot-container">${globalSettings.monetization.in_article_ad_code || '<!-- In-Article Ad Slot -->'}</div>
                </div>
            `;
            if (contentHtml.includes('<h2>')) {
                contentHtml = contentHtml.replace('<h2>', `${adBlock}<h2>`);
            } else {
                contentHtml += adBlock;
            }
        }

        proseEl.innerHTML = contentHtml;
    }

    renderStoryTags(story.tags);
    injectGoogleJsonLdSchema(story);
    setupSocialShareLinks(story);
}

// 4. Render Article Tags
function renderStoryTags(tagsStr) {
    const container = document.getElementById('storyTagsContainer');
    if (!container) return;
    if (!tagsStr) {
        container.style.display = 'none';
        return;
    }
    const tags = tagsStr.split(',').map(t => t.trim()).filter(Boolean);
    if (tags.length === 0) {
        container.style.display = 'none';
        return;
    }
    container.style.display = 'flex';
    container.innerHTML = tags.map(t => `
        <span class="px-3 py-1 rounded-full theme-search-bg border theme-border text-xs font-mono theme-muted">#${t}</span>
    `).join('');
}

// 5. Inject Google JSON-LD Structured Data Schema for Rich Snippets
function injectGoogleJsonLdSchema(story) {
    if (document.getElementById('google-json-ld')) return;
    const script = document.createElement('script');
    script.id = 'google-json-ld';
    script.type = 'application/ld+json';
    script.text = JSON.stringify({
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": story.title,
        "description": story.subtitle || story.title,
        "image": [story.image],
        "datePublished": story.createdAt || new Date().toISOString(),
        "author": [{
            "@type": "Person",
            "name": story.author
        }],
        "publisher": {
            "@type": "Organization",
            "name": globalSettings.site_name || "Medium",
            "logo": {
                "@type": "ImageObject",
                "url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=75"
            }
        }
    });
    document.head.appendChild(script);
}

// 6. Social Share Links (WhatsApp, Twitter/X, Facebook, Copy Link)
function setupSocialShareLinks(story) {
    const currentUrl = window.location.href;
    const shareText = encodeURIComponent(`${story.title} on Medium`);
    const encodedUrl = encodeURIComponent(currentUrl);

    const shareWhatsAppBtn = document.getElementById('shareWhatsAppBtn');
    const shareTwitterBtn = document.getElementById('shareTwitterBtn');
    const shareFacebookBtn = document.getElementById('shareFacebookBtn');

    if (shareWhatsAppBtn) shareWhatsAppBtn.href = `https://api.whatsapp.com/send?text=${shareText}%20${encodedUrl}`;
    if (shareTwitterBtn) shareTwitterBtn.href = `https://twitter.com/intent/tweet?text=${shareText}&url=${encodedUrl}`;
    if (shareFacebookBtn) shareFacebookBtn.href = `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`;
}

window.shareCurrentStory = function() {
    if (navigator.share) {
        navigator.share({
            title: currentStory.title,
            text: currentStory.subtitle || '',
            url: window.location.href,
        }).catch(() => {});
    } else {
        window.copyStoryLink();
    }
};

window.copyStoryLink = function() {
    navigator.clipboard.writeText(window.location.href).then(() => {
        const textSpan = document.getElementById('copyLinkText');
        if (textSpan) {
            const original = textSpan.textContent;
            textSpan.textContent = 'Copied!';
            setTimeout(() => { textSpan.textContent = original; }, 2000);
        }
    }).catch(() => {
        alert('URL copied to clipboard!');
    });
};

// 7. Follow Author Toggle
const followBtn = document.getElementById('followAuthorBtn');
if (followBtn) {
    followBtn.addEventListener('click', () => {
        const isFollowing = followBtn.textContent.trim() === 'Following';
        followBtn.textContent = isFollowing ? 'Follow' : 'Following';
        followBtn.classList.toggle('bg-emerald-600', !isFollowing);
        followBtn.classList.toggle('text-white', !isFollowing);
    });
}

// 8. Dynamic Comments Counter
function updateCommentCounters() {
    const list = document.getElementById('commentList');
    const count = list ? list.children.length : 0;
    
    const countEl = document.getElementById('commentCount');
    const topBadgeEl = document.getElementById('topCommentsBadge');
    
    if (countEl) countEl.textContent = count.toString();
    if (topBadgeEl) topBadgeEl.textContent = count.toString();
}

updateCommentCounters();

const commentForm = document.getElementById('commentForm');
const commentInput = document.getElementById('commentInput');
const commentList = document.getElementById('commentList');

if (commentForm && commentInput && commentList) {
    commentForm.addEventListener('submit', (e) => {
        e.preventDefault();
        const text = commentInput.value.trim();
        if (!text) return;

        const newComment = document.createElement('div');
        newComment.className = 'p-3.5 rounded-xl theme-card border theme-border space-y-1';
        newComment.innerHTML = `
            <div class="flex justify-between font-bold theme-text">
                <span>You</span>
                <span class="text-[10px] theme-muted font-normal">Just now</span>
            </div>
            <p class="theme-text">${text}</p>
        `;
        commentList.prepend(newComment);
        commentInput.value = '';
        updateCommentCounters();
    });
}

// 9. Inject Related Stories
function injectRelatedStories(list, current) {
    const relatedGrid = document.getElementById('relatedStoriesGrid');
    if (!relatedGrid) return;
    const otherStories = list.filter(s => s.slug !== current.slug).slice(0, 3);
    relatedGrid.innerHTML = otherStories.map(s => `
        <a href="post.html?slug=${s.slug}" class="framer-tap block rounded-xl theme-card border theme-border overflow-hidden hover:border-zinc-400 transition-all p-3 space-y-2 group">
            <img src="${s.image}" alt="${s.imageAlt || s.title}" loading="lazy" decoding="async" class="w-full h-28 object-cover rounded-lg">
            <div class="space-y-1">
                <span class="text-[10px] font-mono theme-muted">${s.author} • ${s.readTime}</span>
                <h4 class="text-xs font-bold theme-text group-hover:text-emerald-600 line-clamp-2 leading-snug">${s.title}</h4>
            </div>
        </a>
    `).join('');
}

// 10. Inject Bottom Trending List
function injectTrendingList(list, current) {
    const bottomTrendingList = document.getElementById('bottomTrendingList');
    if (!bottomTrendingList) return;
    const trending = list.filter(s => s.slug !== current.slug).slice(3, 6);
    bottomTrendingList.innerHTML = trending.map(s => `
        <a href="post.html?slug=${s.slug}" class="block space-y-0.5 group">
            <div class="flex items-center gap-2 theme-muted text-[11px] font-mono">
                <span>${s.author}</span>
                <span>•</span>
                <span>${s.date}</span>
            </div>
            <h4 class="font-bold text-xs theme-text group-hover:underline leading-snug">${s.title}</h4>
        </a>
    `).join('');
}

// 11. Light/Dark Theme Switcher Logic
window.toggleTheme = function() {
    const html = document.documentElement;
    const isDark = html.classList.contains('dark');
    if (isDark) {
        html.classList.remove('dark');
        html.classList.add('light');
        localStorage.setItem('medium_theme', 'light');
    } else {
        html.classList.remove('light');
        html.classList.add('dark');
        localStorage.setItem('medium_theme', 'dark');
    }
    updateThemeIcons();
};

function updateThemeIcons() {
    const isDark = document.documentElement.classList.contains('dark');
    document.querySelectorAll('.themeSunSvg').forEach(el => el.classList.toggle('hidden', !isDark));
    document.querySelectorAll('.themeMoonSvg').forEach(el => el.classList.toggle('hidden', isDark));
    
    const badge = document.getElementById('currentThemeBadge');
    if (badge) badge.textContent = isDark ? 'Dark' : 'Light';
}

updateThemeIcons();

// 12. Load Live Story from Supabase Cloud or Local API
async function loadLiveStory() {
    // 1. Try Supabase Cloud first
    if (supabaseClient) {
        try {
            const [artRes, setRes] = await Promise.all([
                supabaseClient.from('articles').select('*'),
                supabaseClient.from('site_settings').select('*').eq('key', 'global_settings').single()
            ]);

            if (!setRes.error && setRes.data && setRes.data.value) {
                globalSettings = Object.assign(globalSettings, setRes.data.value);
                if (globalSettings.brand_color) {
                    document.documentElement.style.setProperty('--accent-green', globalSettings.brand_color);
                }
            }

            if (!artRes.error && artRes.data && artRes.data.length > 0) {
                mediumStories = artRes.data.map(item => ({
                    id: item.id,
                    slug: item.slug,
                    title: item.title,
                    subtitle: item.subtitle,
                    author: item.author,
                    publication: item.publication,
                    authorInitials: item.author_initials,
                    date: item.date,
                    readTime: item.read_time,
                    category: item.category,
                    tags: item.tags,
                    isMember: item.is_member,
                    image: item.image,
                    imageAlt: item.image_alt,
                    bodyHtml: item.body_html,
                    status: item.status
                }));
                const found = mediumStories.find(s => s.slug === currentSlug);
                if (found) currentStory = found;
                renderStoryDetails(currentStory);
                injectRelatedStories(mediumStories, currentStory);
                injectTrendingList(mediumStories, currentStory);
                return;
            }
        } catch(e) {
            console.warn("Supabase fetch failed on post:", e);
        }
    }

    // 2. Fallback to Local API
    try {
        const [articlesRes, settingsRes] = await Promise.all([
            fetch(`${API_BASE}/api/v1/articles`),
            fetch(`${API_BASE}/api/v1/settings`)
        ]);

        if (settingsRes.ok) {
            globalSettings = await settingsRes.json();
            if (globalSettings.brand_color) {
                document.documentElement.style.setProperty('--accent-green', globalSettings.brand_color);
            }
        }

        if (articlesRes.ok) {
            const data = await articlesRes.json();
            if (data.success && data.articles && data.articles.length > 0) {
                mediumStories = data.articles;
                const found = mediumStories.find(s => s.slug === currentSlug);
                if (found) currentStory = found;
            }
        }
    } catch(e) {
        console.warn('API sync fallback to static:', e);
    }
    
    renderStoryDetails(currentStory);
    injectRelatedStories(mediumStories, currentStory);
    injectTrendingList(mediumStories, currentStory);
}

// Initial Load
loadLiveStory();
