<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <title>XML Sitemap – HiveCloud</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
            color: #242424;
            background-color: #fcfcfc;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 960px;
            margin: 0 auto;
            background: #ffffff;
            border: 1px solid #eaeaea;
            border-radius: 16px;
            padding: 32px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.03);
          }
          h1 {
            font-size: 24px;
            font-weight: 800;
            margin: 0 0 8px 0;
            color: #111827;
          }
          p {
            font-size: 14px;
            color: #6b7280;
            margin: 0 0 24px 0;
          }
          .badge {
            display: inline-block;
            background-color: #ecfdf5;
            color: #059669;
            font-size: 12px;
            font-weight: 700;
            padding: 4px 10px;
            border-radius: 9999px;
            border: 1px solid #a7f3d0;
            margin-bottom: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
          }
          th {
            background-color: #f9fafb;
            text-align: left;
            padding: 12px 16px;
            font-weight: 700;
            color: #374151;
            border-bottom: 1px solid #e5e7eb;
          }
          td {
            padding: 12px 16px;
            border-bottom: 1px solid #f3f4f6;
            word-break: break-all;
          }
          tr:hover td {
            background-color: #f9fafb;
          }
          a {
            color: #059669;
            text-decoration: none;
            font-weight: 500;
          }
          a:hover {
            text-decoration: underline;
          }
          .priority {
            font-family: ui-monospace, monospace;
            font-weight: 600;
            color: #4b5563;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="badge">Google Search Console Ready</div>
          <h1>XML Sitemap</h1>
          <p>Generated by HiveCloud Engine for search engines like Google, Bing, and DuckDuckGo.</p>
          <table>
            <thead>
              <tr>
                <th style="width: 55%;">URL Address</th>
                <th style="width: 15%;">Priority</th>
                <th style="width: 15%;">Change Frequency</th>
                <th style="width: 15%;">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td class="priority">
                    <xsl:value-of select="sitemap:priority"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:lastmod"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
